### ISSUE TITLE
Key not found: "couchdb", while starting the Controller.

### ISSUE THREAD

**Issue by Dalfons0** [apache/incubator-openwhisk-deploy-kube#162]
I'm getting some trouble trying to get the the controller service runnning, it seems to start running but then crashes and the pod is restarted, and it keeps doing this indefinitely: 

![image](https://user-images.githubusercontent.com/24602242/37214392-4244ac64-23b5-11e8-8ea0-edad78f894ef.png)

This is the log output:
```
λ kubectl -n openwhisk logs controller-0 -f
[2018-03-09T14:07:18.240Z] [INFO] Initializing Kamon...
[INFO] [03/09/2018 14:07:18.894] [main] [StatsDExtension(akka://kamon)] Starting the Kamon(StatsD) extension
[2018-03-09T14:07:18.990Z] [INFO] Slf4jLogger started
[2018-03-09T14:07:19.350Z] [INFO] Starting remoting
[2018-03-09T14:07:19.594Z] [INFO] Remoting started; listening on addresses :[akka.tcp://controller-actor-system@172.17.0.8:2552]
[2018-03-09T14:07:19.601Z] [INFO] Remoting now listens on addresses: [akka.tcp://controller-actor-system@172.17.0.8:2552]
[2018-03-09T14:07:19.633Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Starting up...
[2018-03-09T14:07:19.713Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[2018-03-09T14:07:19.717Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Started up successfully
[2018-03-09T14:07:19.769Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - No seed-nodes configured, manual cluster join required
[2018-03-09T14:07:20.006Z] [INFO] [??] [Config] environment set value for limits.actions.sequence.maxLength
[2018-03-09T14:07:20.008Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2018-03-09T14:07:20.009Z] [INFO] [??] [Config] environment set value for akka.cluster.seed.nodes
[2018-03-09T14:07:20.010Z] [INFO] [??] [Config] environment set value for controller.instances
[2018-03-09T14:07:20.011Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2018-03-09T14:07:20.012Z] [INFO] [??] [Config] environment set value for controller.localBookkeeping
[2018-03-09T14:07:20.012Z] [INFO] [??] [Config] environment set value for whisk.version.date
[2018-03-09T14:07:20.013Z] [INFO] [??] [Config] environment set value for whisk.version.buildno
[2018-03-09T14:07:20.016Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2018-03-09T14:07:20.019Z] [INFO] [??] [Config] environment set value for kafka.hosts
[2018-03-09T14:07:20.029Z] [INFO] [??] [Config] environment set value for runtimes.manifest
[2018-03-09T14:07:20.030Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2018-03-09T14:07:20.031Z] [INFO] [??] [Config] environment set value for port
[2018-03-09T14:07:20.915Z] [INFO] [??] [KafkaMessagingProvider] topic completed0 already existed
[2018-03-09T14:07:21.253Z] [INFO] [??] [KafkaMessagingProvider] topic health already existed
[2018-03-09T14:07:21.560Z] [INFO] [??] [KafkaMessagingProvider] topic cacheInvalidation already existed
[2018-03-09T14:07:21.952Z] [INFO] [#sid_130] [Controller] starting controller instance 0 [marker:controller_startup0_count:1950]
Exception in thread "main" pureconfig.error.ConfigReaderException: Cannot convert configuration to a whisk.core.database.CouchDbConfig. Failures are:
  at 'whisk':
    - Key not found: 'couchdb'.

        at pureconfig.package$.getResultOrThrow(package.scala:138)
        at pureconfig.package$.loadConfigOrThrow(package.scala:160)
        at whisk.core.database.CouchDbStoreProvider$.makeStore(CouchDbStoreProvider.scala:56)
        at whisk.core.entity.WhiskAuthStore$.datastore(WhiskStore.scala:90)
        at whisk.core.controller.Controller.<init>(Controller.scala:107)
        at whisk.core.controller.Controller$.main(Controller.scala:229)
        at whisk.core.controller.Controller.main(Controller.scala)
[INFO] [03/09/2018 14:07:34.795] [kamon-shutdown-hook-1] [CoordinatedShutdown(akka://kamon)] Starting coordinated shutdown from JVM shutdown hook
[2018-03-09T14:07:34.811Z] [INFO] Starting coordinated shutdown from JVM shutdown hook
[2018-03-09T14:07:34.902Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Exiting completed
[2018-03-09T14:07:34.925Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Shutting down...
[2018-03-09T14:07:34.968Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@172.17.0.8:2552] - Successfully shut down
[2018-03-09T14:07:35.047Z] [INFO] Shutting down remote daemon.
[2018-03-09T14:07:35.060Z] [INFO] [??] [Controller] Shutting down Kamon with coordinated shutdown
[2018-03-09T14:07:35.061Z] [INFO] Remote daemon shut down; proceeding with flushing remote transports.
[2018-03-09T14:07:35.153Z] [INFO] Remoting shut down
[2018-03-09T14:07:35.161Z] [INFO] Remoting shut down.
```
I looked for some solution and I encountered a recent [#PR3369](https://github.com/apache/incubator-openwhisk/pull/3369.)  in the incubator-openwhisk repo, could that have some relation?

**Comment by dgrove-oss** [comment]
yep, #3369 requires some compensating fixes in here on the kube side.  I'm working on it today.  Hope to get a PR together in the next few hours.

**Comment by dgrove-oss** [comment]
https://github.com/apache/incubator-openwhisk-deploy-kube/pull/163 should fix it.  Travis testing running now.

**Comment by Dalfons0** [comment]
Thanks for the quick solve @dgrove-oss, worked like a charm and I finally got the cluster fully deployed :)
