### ISSUE TITLE
Zookeeper fails to start after restarting docker and/or minikube

### ISSUE THREAD

**Issue by sxnguyen** [apache/incubator-openwhisk-deploy-kube#230]
The following error is thrown after minikube and/or docker is restarted in OW+minikube setup (https://github.com/apache/incubator-openwhisk-deploy-kube/tree/master/kubernetes)

==========
2018-06-04 17:44:42,769 [myid:] -ERROR [main:ZooKeeperServerMain@66] -Unexpected exception, exiting abnormallyorg.apache.zookeeper.server.persistence.FileTxnSnapLog$SnapDirContentCheckException: Snapshot directory has log files. Check if dataLogDir and dataDir configuration is correct.at org.apache.zookeeper.server.persistence.FileTxnSnapLog.checkSnapDir(FileTxnSnapLog.java:135)at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:108)at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:112)at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:89)at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:55)at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:119)at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:81)
===========

**Comment by apcheamitru** [comment]
In addition to #231, shouldn't persistent-volumes.yml should be updated?  The host path for both persistent volumes is pointing to /data/pv-zookeeper-01/.
<pre>
[root@localhost ~]# cd incubator-openwhisk-deploy-kube/kubernetes/cluster-setup/
[root@localhost cluster-setup]# grep -A1 hostPath: persistent-volumes.yml
  hostPath:
    path: /data/pv-apigateway-01/
--
  hostPath:
    path: /data/pv-couchdb-01/
--
  hostPath:
    path: /data/pv-kafka-01/
--
  hostPath:
    path: /data/pv-zookeeper-01/
--
  hostPath:
    path: /data/pv-zookeeper-01/
</pre>

Suggested fix:
<pre>
@@ -116,7 +116,7 @@
   capacity:
     storage: 1Gi
   hostPath:
-    path: /data/pv-zookeeper-01/
+    path: /data/pv-zookeeper-01/data/
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
@@ -148,7 +148,7 @@
   capacity:
     storage: 1Gi
   hostPath:
-    path: /data/pv-zookeeper-01/
+    path: /data/pv-zookeeper-01/datalog/
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
</pre>
