### ISSUE TITLE
Invoker was stuck in "ContainerCreating"

### ISSUE THREAD

**Issue by hykych** [apache/incubator-openwhisk-deploy-kube#83]
Using MiniKube, and follow the instruction to deploy.

When I try to deploy invoker, the invoker-0 was stuck in "ContainerCreating".

The log show:
```
{"log":"[2017-11-16T03:34:59.712Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:34:59.713844727Z"}
{"log":"[2017-11-16T03:35:59.769Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:35:59.773521203Z"}
{"log":"[2017-11-16T03:35:59.774Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:35:59.77544446Z"}
{"log":"[2017-11-16T03:36:59.812Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:36:59.814143252Z"}
{"log":"[2017-11-16T03:36:59.813Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:36:59.814279723Z"}
{"log":"[2017-11-16T03:37:59.974Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:38:00.053401421Z"}
{"log":"[2017-11-16T03:38:00.089Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:38:00.093904605Z"}
{"log":"[2017-11-16T03:39:00.266Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:39:00.268608706Z"}
{"log":"[2017-11-16T03:39:00.268Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:39:00.30064349Z"}
{"log":"[2017-11-16T03:40:00.347Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:40:00.359147873Z"}
{"log":"[2017-11-16T03:40:00.360Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:40:00.38143021Z"}
{"log":"[2017-11-16T03:41:00.888Z] [ERROR] [??] [KafkaProducerConnector] sending message on topic 'health' failed: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:41:01.073280485Z"}
{"log":"[2017-11-16T03:41:01.074Z] [ERROR] [??] [Invoker] failed to ping the controller: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.\n","stream":"stdout","time":"2017-11-16T03:41:01.076197685Z"}
```

It seems like the Invoker having trouble connecting to the kafka.

**Comment by daisy-ycguo** [comment]
Can you try `kubectl get pods -n openwhisk` and check the status of each pod, especially Kafka ?

**Comment by hykych** [comment]
@daisy-ycguo 
```
apigateway-2549363043-fth84   1/1       Running             0          3h
controller-0                  1/1       Running             0          1m
controller-1                  1/1       Running             0          1m
couchdb-2360340733-crrpk      1/1       Running             0          3h
invoker-0                     0/1       ContainerCreating   0          48s
kafka-3354284012-5g7sw        1/1       Running             0          2m
redis-3845877026-8cgzn        1/1       Running             0          3h
zookeeper-2112860104-501p8    1/1       Running             0          2m
```
The invoker's status have turned to Running, but still have having trouble connecting to the kafka
I noticed the `adverties.host` property of kafka was set as kafka.openwhisk
Is this mind be related?

**Comment by hykych** [comment]
the log of kafka:
```
[2017-11-16 05:24:18,578] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2017-11-16 05:24:18,587] INFO [KafkaApi-0] Auto creation of topic cacheInvalidation with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2017-11-16 05:24:18,630] ERROR [KafkaApi-0] Error when handling request {group_id=cacheInvalidationcontroller0} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:24:19,489] ERROR [KafkaApi-0] Error when handling request {group_id=health0} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:24:19,569] ERROR [KafkaApi-0] Error when handling request {group_id=completions} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:24:19,763] ERROR [KafkaApi-0] Error when handling request {group_id=cacheInvalidationcontroller1} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:24:20,714] ERROR [KafkaApi-0] Error when handling request {group_id=completions} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:24:20,720] ERROR [KafkaApi-0] Error when handling request {group_id=health1} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:25:09,593] ERROR [KafkaApi-0] Error when handling request {group_id=invokers} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-16 05:33:36,044] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 4 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2017-11-16 05:43:36,060] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 10 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2017-11-16 05:53:36,064] INFO [Group Metadata Manager on Broker 0]: Removed 0 expired offsets in 12 milliseconds. (kafka.coordinator.GroupMetadataManager)

```

**Comment by daisy-ycguo** [comment]
Did you change any settings of Kafka in `kubernetes/kafka/kafka.yml`? The log msg said `replication factor: 3 larger than available brokers: 1`.

**Comment by hykych** [comment]
@daisy-ycguo I did not change that.

**Comment by hykych** [comment]
@daisy-ycguo 
I use `kubectl exec -it kafka-3354284012-5g7sw -n openwhisk sh` to get inside the pod.
And then execute `echo $REPLICATION_FACTOR`.
The value is 1, not 3

**Comment by dgrove-oss** [comment]
@hykych any update from your side?  I have not been able to reproduce this problem.

**Comment by dgrove-oss** [comment]
See the comments in #105, maybe some of them apply?
